### ISSUE TITLE
when loading skeleton view conditionally its not working

### ISSUE THREAD

**Issue by swiftserieschannel** [alexZajac/react-native-skeleton-content#11]
when loading skeleton view conditionally its not working.

**Comment by swiftserieschannel** [comment]
![Screenshot 2020-03-17 at 7 53 29 PM](https://user-images.githubusercontent.com/48859783/76865662-0f04c300-6889-11ea-852a-989a0f7b64c1.png)

**Comment by tr3v3r** [comment]
@swiftserieschannel, it known issue for now. The problem is that skeleton animation will run after `loading `  updates from `false` to `true`. So in your example, your `loading` will be `true` on the very first render, and animation won't run. 
As a workaround, you can rewrite a bit of your JSX. i.e:
```
<SceletonContent isLoading={props.isLoading}>
 {props.isLoading ?  <HeaderComponent /> : null }
</SceletonContent>

```

Don't forget to add corresponding layout for SceletoContent

**Comment by alexZajac** [comment]
Hello @swiftserieschannel! Yes totally, it is an actual expected behavior. If it wasn't, then there will be no need for a `isLoading` prop! You should pass props.isLoading to the component!
